FEAT - a funcionalidade quartos serve para cadastrar um novo quarto
nicolasgandrade/fp2 pull request #13
Opened 2022-10-31 21:31 UTC by CamargoLucasD

2022-11-03 20:20 UTC, nicolasgandrade approved these changes
Boa! Só o nome do PR que poderia ter sido melhor, mas de boa.

2022-11-04 00:06 UTC, ViniciusKalach requested changes
Fazer as modificações requisitadas.

2022-11-04 00:06 UTC, ViniciusKalach commented on src/view/Quartos.java
> +        jPanel1 = new javax.swing.JPanel();
Alterar o nome dos Panel para a sigla "jp(nome do jPanel)". Ex.: ao invés de JPanel1, deixe jp1.

2022-11-04 00:06 UTC, ViniciusKalach commented on src/view/Quartos.java
> +        jLabel1 = new javax.swing.JLabel();
Mudar nome das variáveis seguindo o padrão: Além do jPanel ali em cima, tem que mudar esse jLabel também. 
Label => lblSuaLabel;

2022-11-04 00:11 UTC, JoseMRezende requested changes
Mudar nome das variáveis

2022-11-04 00:15 UTC, ViniciusKalach commented on src/view/Quartos.java
> +        jLabel1 = new javax.swing.JLabel();
OBS.: apagar os comentários 👍

2022-11-04 00:50 UTC, nicolasgandrade commented on src/view/Quartos.java
> +        jLabel1 = new javax.swing.JLabel();
Esse meu mano Vinicius tá mandando muito nos code review. Fala deleeeeee

2022-11-07 01:10 UTC, nicolasgandrade approved these changes

2022-11-07 01:10 UTC, merged