FEAT - Cria reservas quartos
nicolasgandrade/fp2 pull request #14
Opened 2022-10-31 22:02 UTC by CamargoLucasD

2022-11-03 20:17 UTC, nicolasgandrade requested changes
Mudanças bem simples pra fazer.

2022-11-03 20:17 UTC, nicolasgandrade commented on src/view/ReservasQuartos.java
> + */
Remover comentários

2022-11-03 20:17 UTC, nicolasgandrade commented on src/view/ReservasQuartos.java
> + */
Remover comentários

2022-11-03 20:17 UTC, nicolasgandrade commented on src/view/ReservasQuartos.java
> +    private javax.swing.JLabel lbllSaida;
Tem um "l" a mais em lblSaida (está escrito lbllSaida)

2022-11-04 00:11 UTC, JoseMRezende approved these changes
Joia

2022-11-04 00:12 UTC, ViniciusKalach approved these changes
Aprovado, meu chapinha.

2022-11-04 00:48 UTC, nicolasgandrade approved these changes

2022-11-04 00:49 UTC, merged