Feat/controller reservas
nicolasgandrade/fp2 pull request #23
Opened 2022-11-11 21:36 UTC by ViniciusKalach

Cria o controle dos reservas e modifica o view, mas ainda falta completar umas coisinhas.

2022-11-11 22:32 UTC, nicolasgandrade requested changes

2022-11-11 22:32 UTC, nicolasgandrade commented on src/controller/ControllerReserva.java
> +    public void inserirQuarto(Reserva reserva){
Método com nome errado. Isso é um controller de reserva não de Quartos

2022-11-11 22:32 UTC, nicolasgandrade commented on src/controller/ControllerReserva.java
> +        String sql = "INSERT INTO Quartos(numero_quarto, hospede_id, entrada, saida) VALUES("
SQL errado. Está inserindo dados na tabela de Quartos, você deve inserir uma nova reserva.

2022-11-11 22:32 UTC, nicolasgandrade commented on src/controller/ControllerReserva.java
> +                + reserva.getQuarto()+ ","
Aqui você não pode inserir no banco um Objeto, é apenas um id. Precisa pegar o id do quarto, não o quarto como um todo.

2022-11-11 22:32 UTC, nicolasgandrade commented on src/controller/ControllerReserva.java
> +                + reserva.getHospede()+ ","
Mesmo de cima

2022-11-12 19:18 UTC, nicolasgandrade commented on src/controller/ControllerReserva.java
> +                + reserva.getEntrada()+ ","
Chegou a testar isso?  A data no SQL segue o seguinte formato: "yyyy-MM-dd hh:mm:ss". Está inserindo corretamente?
Aliás, se está funcionando, tenta dar um select ou pegar o acesso do felipe só pra verificar como tá chegando lá no banco

2022-11-15 16:07 UTC, closed without merging

2022-11-15 19:35 UTC, ViniciusKalach commented
@CamargoLucasD por que fechou? kkkkk

2022-11-15 20:08 UTC, CamargoLucasD commented
Em ter., 15 de nov. de 2022 às 16:36, Vinícius Kalach <
***@***.***> escreveu:

> @CamargoLucasD <https://github.com/CamargoLucasD> por que fechou? kkkkk
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nicolasgandrade/fp2/pull/23#issuecomment-1315777805>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2WZA7EE5FGUHN3NXFGHPZTWIPQ2PANCNFSM6AAAAAAR56RZ74>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>