Feat/listagem quartos
nicolasgandrade/fp2 pull request #34
Opened 2022-11-21 01:07 UTC by ViniciusKalach

Cria a função de listar os quartos na aba de quartos do sidenav.

2022-11-21 03:10 UTC, nicolasgandrade requested changes
Está dando conflito com a master (eu mesmo vou tentar arrumar). Isso acontece quando você criou a branch a partir de uma versão antiga da master, ou seja, não deu `git pull` antes de criar a branch, ou criou e ela ficou parada sem você atualizá-la.

Tem algumas mudanças a serem feitas.

2022-11-21 03:10 UTC, nicolasgandrade commented on src/controller/ControllerListarQuartos.java
> +    public ArrayList ListarQuartos(int número) throws SQLException{
Métodos devem começar com letra minúscula

2022-11-21 03:10 UTC, nicolasgandrade commented on src/controller/ControllerListarQuartos.java
> +        Quarto quarto = new Quarto();
A instanciação de um novo quarto deve ser dentro do while

2022-11-21 03:10 UTC, nicolasgandrade commented on src/controller/ControllerListarQuartos.java
> +        return quartos;
return this.quartos;

2022-11-21 03:10 UTC, nicolasgandrade commented on src/controller/ControllerListarQuartos.java
> +            if (this.conn.getResultSet().toString().equals("ocupado")){
Não seria `this.conn.getResultSet().getString("ocupado").equals("ocupado")?

2022-11-21 03:11 UTC, nicolasgandrade commented
Conflitos resolvidos.

2022-11-22 02:59 UTC, ViniciusKalach commented
@nicolasgandrade , agora tá bala.

2022-11-22 16:36 UTC, nicolasgandrade approved these changes

2022-11-22 16:36 UTC, merged