FEAT - criar classes de quarto e categoria
nicolasgandrade/fp2 pull request #4
Opened 2022-10-14 21:30 UTC by ViniciusKalach

São três arquivos .java na pasta de model. Criação das classes de quarto(QuartosClass.java) e de categoria(CategoriaClass.java), com estas ultimas preenchidas(Categorias.java).

2022-10-14 22:33 UTC, nicolasgandrade requested changes
Fazer mudanças solicitadas

2022-10-14 22:33 UTC, nicolasgandrade commented on src/model/QuartosClass.java
> +public class QuartosClass {
Mudar nome da classe para apenas Quarto.

Pense nas classes como algo que representam a realidade.

2022-10-14 22:33 UTC, nicolasgandrade commented on src/model/QuartosClass.java
> +    private int categora_id;
Não deve receber um inteiro categoriaId, mas sim um objeto do tipo Categoria.
Classes de um sistema orientado a objetos não funcionam como o banco de dados, você deve usar as próprias classes dentro de outras.

`private Categoria categoria;`

2022-10-14 22:33 UTC, nicolasgandrade commented on src/model/QuartosClass.java
> +
Daqui pra baixo, mudar de acordo com os comentários acima.

2022-10-14 22:33 UTC, nicolasgandrade commented on src/model/CategoriasClass.java
> +public class CategoriasClass {
Mudar o nome da classe para apenas Categoria.

2022-10-14 22:33 UTC, nicolasgandrade commented on src/model/Categorias.java
> +
O que seria essa classe?

Classe deve ser algo reproduzível, que possa ser instanciada diversas vezes (a não ser em casos específicos). No momento esse arquivo não faz sentido, pode capar fora.

2022-10-14 22:33 UTC, nicolasgandrade commented on src/model/CategoriasClass.java
> +
Por que o package de todos os arquivos não está como view e sim Classes?
Trocar para view.

2022-10-15 19:41 UTC, ViniciusKalach commented
@nicolasgandrade , arrumei os erros.

2022-10-15 21:14 UTC, nicolasgandrade approved these changes

2022-10-15 21:14 UTC, nicolasgandrade commented on src/model/CategoriasClass.java
> +package Classes;
`package model`

2022-10-15 21:14 UTC, nicolasgandrade commented on src/model/QuartosClass.java
> +package Classes;
`package model`

2022-10-15 21:15 UTC, nicolasgandrade commented
Show, já vou dar merge. Parabéns!

2022-10-15 21:16 UTC, merged