FEAT - criar slidenav
nicolasgandrade/fp2 pull request #9
Opened 2022-10-21 00:58 UTC by ViniciusKalach

Criar menu slidenav junto com as abas da tela de listagem de quartos, de hospedes cadastrados e de usuários. De funcional no momento só há os botões de navegação. Junto a este commit foi enviado também as imagens que serão usadas (para o menu, para a lupa e para o fundo dos panel). OBS: Nós resolvemos não implementar as imagens nesta interface porque o bug não foi corrigido, elas estão apenas armazenadas em "assets".

2022-10-21 23:21 UTC, nicolasgandrade requested changes
Fazer mudanças solicitadas

2022-10-21 23:21 UTC, nicolasgandrade commented on src/view/ViewSlideNav.java
> +public class ViewSlideNav extends javax.swing.JFrame {
Mudar nome SideNav. (E é sIdeNav, não sLidenav).

2022-10-21 23:21 UTC, nicolasgandrade commented on src/view/ViewSlideNav.java
> +    public ViewSlideNav() {
Mesmo de antes.

2022-10-23 01:35 UTC, ViniciusKalach commented
Correção feita.

2022-10-23 21:30 UTC, nicolasgandrade requested changes
Fazer as mudanças nos nomes das variáveis conforme indicado e remover arquivo "lupa_icon.png" fora de assets duplicado, deixar apenas o que está usando.

2022-10-23 21:30 UTC, nicolasgandrade commented on src/view/ViewSideNav.java
> +    private javax.swing.JLabel jLabel1;
Mudar nome das variáveis seguindo o padrão: 
Label => lblSuaLabel;
Text Field => txtSeuTextField;

2022-10-23 21:31 UTC, nicolasgandrade commented on src/view/ViewSideNav.java
> +    private javax.swing.JLabel jLabel1;
Os botões estão corretos.

2022-10-25 21:11 UTC, ViniciusKalach commented
Feito, commitei. Manda bala.

2022-10-25 22:06 UTC, JoseMRezende approved these changes
ok

2022-10-26 14:32 UTC, nicolasgandrade requested changes

2022-10-26 14:32 UTC, nicolasgandrade commented on src/view/ViewSideNav.java
> +    private javax.swing.JTextField tfHost;
Mudar variáveis de text field para o padrão txtNomeDoTextField.
Adendo: Acho que faz sentido sim ser tf, mas como no resto do projeto já está padronizado como txt é melhor trocar só aqui em vez de refatorar todo o resto. Quando tiver com um tempinho vou escrever todos esses padrões no README do projeto.

2022-10-26 20:29 UTC, ViniciusKalach commented
Ok, modificações feitas.

2022-10-26 22:28 UTC, nicolasgandrade approved these changes

2022-10-26 22:28 UTC, merged